This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./proyecto.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file proyecto.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (19 comparisons).
Generating output file proyecto.acr....done (14 lines written, 0 warnings).
Output written in proyecto.acr.
Transcript written in proyecto.alg.
