This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./proyecto.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file proyecto.acn....done (26 entries accepted, 0 rejected).
Sorting entries....done (125 comparisons).
Generating output file proyecto.acr....done (32 lines written, 0 warnings).
Output written in proyecto.acr.
Transcript written in proyecto.alg.
